name: Deploy to itch.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Deploy to itch.io
        uses: Ayowel/butler-to-itch@v1.3.0
        with:
          butler_key: ${{ secrets.BUTLER_API_KEY }}
          itch_user: kolja_sam
          itch_game: global-delivery
          auto_channel: false
          files: |
            html5 dist
